# Generated by Django 5.2 on 2026-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI estimate')], max_length=12)),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
